name: tradenote
services:
  mongo:
    image: mongo:latest
    container_name: tradenote_db
    volumes:
      - tradenote_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tn
      MONGO_INITDB_ROOT_PASSWORD: tn
      MONGO_INITDB_DATABASE: tradenote
    networks:
      - tradenote_net

  tradenote:
    image: eleventrading/tradenote
    container_name: tradenote_app
    ports:
      - 8080:8080
    environment:
      MONGO_URI: mongodb://tn:tn@mongo:27017/tradenote?authSource=admin
      TRADENOTE_DATABASE: tradenote
      APP_ID: 123456
      MASTER_KEY: 123456
      TRADENOTE_PORT: 8080
    depends_on:
      - mongo
    networks:
      - tradenote_net

  mongoexpress:
    image: mongo-express
    container_name: mongo-express_app
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://tn:tn@mongo:27017/tradenote?authSource=admin&ssl=false
      ME_CONFIG_BASICAUTH_ENABLED: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: tn
      ME_CONFIG_BASICAUTH_PASSWORD: tn
      PORT: 8081

    depends_on:
      - mongo
    networks:
      - tradenote_net

networks:
  tradenote_net:
    driver: bridge

volumes:
  tradenote_db:
    name: tradenote_db